import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavLinks from "./ui/nav-links";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html>
      <body>
        <div className="grid grid-cols-5 h-screen">
          <div className="h-full p-6 md:overflow-y-auto md:p-12 bg-gradient-to-r from-sky-900 to-sky-200"><NavLinks /></div>
          <div className="col-span-4 p-6 md:overflow-y-auto md:p-12 bg-gradient-to-r from-sky-200 to-sky-900">{children}</div>
        </div>
    </body>
    </html>
  );
}